version: 2

updates:
  # Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
    groups:
      all:
        patterns:
          - "*"
  # Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
