version: 2

updates:
  # Go
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        patterns:
          - "*"
  # Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      all:
        dependency-type: "production"
