version: "2"
run:
  build-tags:
    - testing
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - goconst
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam
  disable:
    - depguard
    - dupl
    - errcheck
    - lll
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gosec:
      excludes:
        - G115
    govet:
      enable:
        - shadow
    lll:
      line-length: 150
      tab-width: 1
    misspell:
      locale: UK
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
