version: "2"
run:
  concurrency: 4
  tests: false
  allow-parallel-runners: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - goconst # Finds repeated strings that could be replaced by a constant.
    - gocyclo # Computes and checks the cyclomatic complexity of functions.
    - gosec # Inspects source code for security problems.
    - misspell # Finds commonly misspelled English words.
    - nakedret # Checks that functions with naked returns are not longer than a maximum size (can be zero).
    - prealloc # Finds slice declarations that could potentially be pre-allocated.
    - unconvert # Remove unnecessary type conversions.
    - errcheck # Errcheck is a program for checking for unchecked errors in Go code. These unchecked errors can be critical bugs in some cases.
  disable:
    - depguard # Go linter that checks if package imports are in a list of acceptable packages.
    - dupl # Detects duplicate fragments of code.
  settings:
    gosec:
      excludes:
        - G115
    errcheck:
      check-type-assertions: true
      check-blank: false
    goconst:
      min-len: 3
      min-occurrences: 3
    lll:
      line-length: 150
      tab-width: 1
    misspell:
      locale: UK
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
