apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: msn-exception-list
    files:
      - msn_exception_list.tsv=resources/msn_exception_list.tsv
generatorOptions:
  disableNameSuffixHash: true
