// Code generated by MockGen. DO NOT EDIT.
// Source: eligibility.go

// Package mock_gateway is a generated GoMock package.
package mock_gateway

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	eligibilityv1 "github.com/utilitywarehouse/energy-contracts/pkg/generated/smart_booking/eligibility/v1"
	grpc "google.golang.org/grpc"
)

// MockEligibilityClient is a mock of EligibilityClient interface.
type MockEligibilityClient struct {
	ctrl     *gomock.Controller
	recorder *MockEligibilityClientMockRecorder
}

// MockEligibilityClientMockRecorder is the mock recorder for MockEligibilityClient.
type MockEligibilityClientMockRecorder struct {
	mock *MockEligibilityClient
}

// NewMockEligibilityClient creates a new mock instance.
func NewMockEligibilityClient(ctrl *gomock.Controller) *MockEligibilityClient {
	mock := &MockEligibilityClient{ctrl: ctrl}
	mock.recorder = &MockEligibilityClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEligibilityClient) EXPECT() *MockEligibilityClientMockRecorder {
	return m.recorder
}

// GetMeterpointEligibility mocks base method.
func (m *MockEligibilityClient) GetMeterpointEligibility(ctx context.Context, in *eligibilityv1.GetMeterpointEligibilityRequest, opts ...grpc.CallOption) (*eligibilityv1.GetMeterpointEligibilityResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMeterpointEligibility", varargs...)
	ret0, _ := ret[0].(*eligibilityv1.GetMeterpointEligibilityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeterpointEligibility indicates an expected call of GetMeterpointEligibility.
func (mr *MockEligibilityClientMockRecorder) GetMeterpointEligibility(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeterpointEligibility", reflect.TypeOf((*MockEligibilityClient)(nil).GetMeterpointEligibility), varargs...)
}
