-- +migrate Up
UPDATE booking SET booking_type = 1
WHERE booking_type IS NULL;
UPDATE booking SET status = 0
WHERE status IS NULL;
ALTER TABLE IF EXISTS booking ALTER COLUMN booking_type SET NOT NULL;
ALTER TABLE IF EXISTS booking ALTER COLUMN booking_type SET DEFAULT 0;
ALTER TABLE IF EXISTS booking ALTER COLUMN status SET NOT NULL;
ALTER TABLE IF EXISTS booking ALTER COLUMN status SET DEFAULT 0;
ALTER TABLE IF EXISTS booking ALTER COLUMN external_reference SET NOT NULL;
-- +migrate Down
ALTER TABLE IF EXISTS booking ALTER COLUMN booking_type DROP NOT NULL;
ALTER TABLE IF EXISTS booking ALTER COLUMN booking_type DROP DEFAULT;
ALTER TABLE IF EXISTS booking ALTER COLUMN status DROP NOT NULL;
ALTER TABLE IF EXISTS booking ALTER COLUMN status DROP DEFAULT;
ALTER TABLE IF EXISTS booking ALTER COLUMN external_reference DROP NOT NULL;
