name: Build energy-smart-booking-services

on:
  workflow_call:

jobs:
  opt-out:
    uses: ./.github/workflows/build_service_reusable_workflow.yml
    with:
      source_files: cmd/opt-out
      service: energy-smart-booking-opt-out
    secrets: inherit

  eligibility:
    uses: ./.github/workflows/build_service_reusable_workflow.yml
    with:
      source_files: cmd/eligibility
      service: energy-smart-booking-eligibility
    secrets: inherit

  lowribeck-api:
      uses: ./.github/workflows/build_service_reusable_workflow.yml
      with:
        source_files: cmd/lowribeck-api
        service: energy-smart-booking-lowribeck-api
      secrets: inherit

  booking-api:
    uses: ./.github/workflows/build_service_reusable_workflow.yml
    with:
      source_files: cmd/booking-api
      service: energy-smart-booking-api
    secrets: inherit

  booking-click:
    uses: ./.github/workflows/build_service_reusable_workflow.yml
    with:
      source_files: cmd/click-generator
      service: energy-smart-booking-click-generator
    secrets: inherit

  internal:
    uses: ./.github/workflows/build_service_reusable_workflow.yml
    with:
      source_files: internal
      service: 
    secrets: inherit
