name: Build energy-smart-booking-services

on:
  workflow_call:

jobs:
  opt-out:
    uses: ./.github/workflows/build_service_reusable_workflow.yml
    with:
      source_files: cmd/opt-out
      service: energy-smart-booking-opt-out
      subpackage: "opt-out"
    secrets: inherit

  eligibility:
    uses: ./.github/workflows/build_service_reusable_workflow.yml
    with:
      source_files: cmd/eligibility
      service: energy-smart-booking-eligibility
      subpackage: "eligibility"
    secrets: inherit

  lowribeck-api:
      uses: ./.github/workflows/build_service_reusable_workflow.yml
      with:
        source_files: cmd/lowribeck-api
        service: energy-smart-booking-lowribeck-api
      subpackage: "lowribeck-api"
      secrets: inherit

  booking-api:
    uses: ./.github/workflows/build_service_reusable_workflow.yml
    with:
      source_files: cmd/booking-api
      service: energy-smart-booking-api
      subpackage: "api"
    secrets: inherit
